// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLA2gxdMKrKSDVqUt1IcQA8-7IjINVeI',
    appId: '1:680595753791:web:a57120f627a9cc5927a18a',
    messagingSenderId: '680595753791',
    projectId: 'formatiom',
    authDomain: 'formatiom.firebaseapp.com',
    storageBucket: 'formatiom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0xirZhwtGxqmuO3PIzjDaHlYwXxBtk9c',
    appId: '1:680595753791:android:f639822f74c593f727a18a',
    messagingSenderId: '680595753791',
    projectId: 'formatiom',
    storageBucket: 'formatiom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSrtQSHgTdLdYfStZZ4cTawZ4Rv6twsGk',
    appId: '1:680595753791:ios:0f3b2a1a68c105cc27a18a',
    messagingSenderId: '680595753791',
    projectId: 'formatiom',
    storageBucket: 'formatiom.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFormatiom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSrtQSHgTdLdYfStZZ4cTawZ4Rv6twsGk',
    appId: '1:680595753791:ios:5af1b49f55e322a027a18a',
    messagingSenderId: '680595753791',
    projectId: 'formatiom',
    storageBucket: 'formatiom.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFormatiom.RunnerTests',
  );
}
